name: my action

on: 
  push:
    branches:[main]

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # - name: Clone Repository
      #   uses: actions/checkout@v3
      - name: Install Dependancies
        run: |
          echo "Running Installing Dependancies ..."
          yarn install
      - name: Run Linting
        run: |
          echo "Running Linting test ..."
          yarn lint
        env:
          CI: true
      
  securityCheck:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for Security
        run: |
          echo "Running Security Checks .."
          sleep 5s;
          echo "Running Security Checks .. 1"
          sleep 5s;
          echo "Running Security Checks .. 2"
          sleep 5s;
          echo "Running Security Checks .. 3"
          sleep 5s;
          echo "Running Security Checks .."
          sleep 5s;
      